service:
  name: ringcentral-engage-voice-embeddable-mobile
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 256
  environment: ${file(./env.yml)}
  profile: default
  excludeDevDependencies: true
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: "*"
deploymentBucket:
  tags:
    department: dev
    Owner: Your name
    Stage: production
    Environment: your-env-tag
    Team: your-team
    Name: ringcentral-engage-voice-embeddable-mobile
package:
  include:
    - '*.json'
    - '*.js'
    - 'node_modules/**'
functions:
  app:
    handler: lambda.app
    timeout: 400 # 5 miutes
    # role: arn:aws:iam::111111:role/xxxx-prod-us-east-1-lambdaRole
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
